site_name: ABI Documentation
copyright: Copyright &copy; 2021 Alpha Blend Interactive
site_url: https://docs.abinteractive.net
repo_name: Alpha-Blend-Interactive/docs
repo_url: https://github.com/Alpha-Blend-Interactive/docs

theme:
  name: material
  logo: assets/images/abi-small-white.png
  favicon: assets/images/favicon.png
  features:
    - navigation.instant
    - navigation.section
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - navigation.indexes
  palette:
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    # Light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  custom_dir: overrides/
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js
extra:
  generator: false
  alternate:
    # Switch to English
    - name: English
      link: /
      lang: en

    # Switch to German
    #- name: Deutsch
    #  link: /de/
    #  lang: de

    # Switch to Japanese
    #- name: 日本語
    #  link: /ja/
    #  lang: ja

plugins:
  - awesome-pages
  - extra-sass
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - build: true
          default: false
          locale: de
          name: Deutsch
        - build: true
          default: false
          locale: ja
          name: 日本語
      reconfigure_material: true
      reconfigure_search: true
  - search
  - markdownextradata:
      data: ./_variables

markdown_extensions:
  - attr_list
  - meta
  - toc:
      permalink: true
  - codehilite
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition